# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='uri',
            name='uri_number',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
