# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180526_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='uri',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
