# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_uri_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uri',
            old_name='uri_title',
            new_name='title',
        ),
    ]
